### ISSUE TITLE
LCFS - BUG - Internal statuses are incorrectly visible on the BCeID

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#2050]
**Describe the Bug:**  
Internal statuses are incorrectly visible on the **BCeID** side of the application. These statuses should only be displayed for **IDIR** users and not be accessible to BCeID users. See attached screen capture for reference.

![Image](https://github.com/user-attachments/assets/485b0055-9bf0-4871-a4b5-f63c43cbdb63)

**Expected Behaviour:**  
- Internal 'Recommended' statuses should **not** be visible to **BCeID** users.  
- Only **publicly relevant statuses** should be displayed on the **BCeID** side.  
- Internal statuses should remain visible only to **IDIR** users.  

**Actual Behaviour:**  
- Internal statuses are appearing on the **BCeID** side.  
- Users with **BCeID** accounts can see statuses that should be restricted.  

**Implications:**  
- Potential **data exposure** of internal process statuses.  
- Could lead to **user confusion** as BCeID users may not understand internal statuses.  
- May **compromise workflow transparency** by exposing unnecessary details to external users.  

**Steps To Reproduce:**  
1. Log in as a **BCeID** LCFS2 user.  
2. Navigate to a compliance reporting index.  
3. Observe that **internal statuses** are visible when they should not be.

**Comment by hamed-valiollahi** [comment]
Previously, filtering for submitted statuses for BCEID users caused a 500 error. This issue has been fixed in this PR.

**Comment by airinggov** [comment]
This doesn't appear to be fixed, still seeing recommended by analyst as a BCeID user
