### ISSUE TITLE
LCFS - Internal commenting feature for IDIR users 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#259]
**Description:**
To build a commenting feature that enables government users to communicate with each other (internally) while reviewing and processing different submissions in the LCFS portal, including transfers, compliance reports, and other transactions (i.e., administrative adjustment, Initiative Agreement issuance). 

This card is to build the internal commenting feature for use within the transfers feature. However, we will want to also use the internal commenting feature within other features yet to be developed. Therefore, we should develop this feature with plug-and-play reusability in mind. 

Note: ZEVA has similar functionality; it may be worth discussing with developers from the Zelda team; there may be potential to repurpose / reuse some of their code/work. 

**Requirements:**
- Free text field
- Simple markup functionality (ZEVA has this; very basic which is all we need, don't want overly complex formatting features; see screenshot below)
- Optional feature (not required to be used in order to take actions on transfers)
- 'Add comment' button allows the user to save their comment 
- Saved comments are displayed immediately after being saved; includes displaying the name of the person who added the comment and the date & time it was saved / added.
- Saved comments are displayed in descending order (newest comment at the top of the comment chain)
- Feature is only visible to IDIR users, including saved comments
- Government users can add multiple comments (no limit)
- There are no restrictions on when government users can add / edit comments. For example, an analyst can add/edit a comment before or after they make a recommendation to the director; they can also / add edit the comment after the transfer has been recorded / refused. 
- Editing comments will be handled in separate card. It is worth mentioning that we will want to track the date the original comment was added/saved as well as the date the comment was edited; in cases of multiple edits, we will want to display the date the last edit was made (while also still displaying the date the original comment was first added/saved).

**Wireframes:**
- Government Analyst comments: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001087/simulate/no-panels
- Government Director comments: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001091/simulate/no-panels
- Screenshot of simple markup functionality in ZEVA: 
<img width="788" alt="MicrosoftTeams-image" src="https://github.com/bcgov/lcfs/assets/2143103/7c57563b-7bed-46a7-931e-c65e28cc7850">

**Purpose and benefit to user:**
Enables internal government communication about the transfer. Purposely designed to be a standalone feature that will be reused within other features. Will allow submission-specific review and analyses to be communicated to the director to support their decision-making on whether to approve/accept/record different items. 

**Acceptance Criteria:**
- [ ] Create a new Comment route handler in the backend, that has a post handler for creating new comments, passing the comment type, and transfer or issuance id.
- [ ] Given I am a government user, when I add a comment on a transfer, then it should be saved and displayed immediately with my name and the current date and time.
- [ ] Given I am a government user, when I view the comment section of a transfer, then I should see all comments in descending order, starting with the newest.

**Development Checklist:**

- [ ] Implement free text field with basic markup functionality.
- [ ] Create 'Add comment' button with immediate display functionality for comments.
- [ ] Ensure comments are displayed in descending order and restricted to IDIR users.
- [ ] Use the existing commentInput component in ZEVA for reference

**Notes:**
In ZEVA they have a great comment component linked here: https://github.com/bcgov/zeva/blob/release-1.58.0/frontend/src/app/components/CommentInput.js
here is a use case: 
https://github.com/bcgov/zeva/blob/release-1.58.0/frontend/src/compliance/components/AssessmentDetailsPage.js

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/259?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/259?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by hamed-valiollahi** [comment]
@Grulin, Thanks Lindsy, for your comment. I couldn't reproduce the issue you mentioned. It's possible that it's already fixed in the latest version of the code I have. I have both `Government` and `Analyst` roles.  Could you please try again?

**Comment by Grulin** [comment]
Hi @hamed-valiollahi. Thanks for looking in to this. I'm still getting the same error. It may be something to do with the user role maybe? 'Government' should not be a user role anymore. This feature should be available to an IDIR user with the 'analyst' role. I tried again today and get the following error:



![Image](https://github.com/bcgov/lcfs/assets/156380046/4e7ce7cd-0841-4196-84c3-ee48ed576b52)

Please let me know what you think. Thank you.

**Comment by hamed-valiollahi** [comment]
Hi @Grulin, I've created a PR for this issue, hoping that it resolves the issue.
Please let me know if there are any other issues. Thank you!
