### ISSUE TITLE
LCFS - Fuel codes, add Contact name and Contact email

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#647]
**Description:** The business area would like to add optional contact information (name and email) to fuel codes to help notify fuel producers when fuel codes are near expiry.

**Wireframe:** 
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/168739509?mode=m

**Purpose and benefit to user:** The business area would like to investigate having LCFS automate 90 alerts for expiring fuel codes. Fuel producers would receive an email to update their fuel codes.

**Acceptance Criteria:**

- [ ] Given I am a IDIR users, When I am adding fuel code info, then I can add an optional Contact name and Contact email.
- [ ] Given I am a IDIR users, When I am adding fuel code info, when I am filling out these fields, it should display predictive text based on what is already available in the database
- [ ] Given I am a IDIR users, When I am adding fuel code info, when selecting a fuel code, the contact name and contact email should be autofilled based on the last fuel code data

**Dev Notes**
- [ ] add `Contact Name` and `Contact Email` to the schema
- [ ] use `autocompleteEditor` for those fields
- [ ] add the data to the `table-options` endpoint
- [ ] change the fuel code auto populate to include the above fields

**Notes:** Fuel producers are not the same as fuel suppliers. They are not users of TFRS/LCFS, they may not operate in BC and may not be eligible to get a Business BCeID.

**Comment by airinggov** [comment]
@AlexZorkin @kevin-hashimoto receiving a 500 error accessing the fuel code page and the new fuel code button also gives an error so these cards can't be tested

**Comment by kevin-hashimoto** [comment]
@airinggov I believe this should be fixed on dev now. we had a problem with the seeders

**Comment by Grulin** [comment]
The 'Contact name', 'Contact email' columns should be optional but they are currently showing as required. 

'Former company' is also showing as required and it should be optional instead.

**Comment by Grulin** [comment]
The column "Former company" is still showing up as a required field. This should not be a required field:


![Image](https://github.com/bcgov/lcfs/assets/156380046/01eed987-639d-4445-a7a7-360ef894b0f5)

**Comment by airinggov** [comment]
contact email is still not saving when null

![Image](https://github.com/bcgov/lcfs/assets/20462387/a76d4558-0ffc-4fd9-8442-6b93c0f27827)
