### ISSUE TITLE
Refactor FuelCode Component to New agGrid Setup

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#811]
## Description
Refactor the FuelCode component to use our new agGrid setup, similar to the recently refactored FuelSupply component. This will improve consistency across our application and potentially enhance performance and maintainability.

## Purpose and Benefit to User
- Improve consistency in user interface and behavior across different parts of the application
- Potentially enhance performance and responsiveness of the FuelCode grid
- Simplify future maintenance and feature additions by aligning with our new standard setup

## Acceptance Criteria
1. The FuelCode component uses the new agGrid setup, matching the structure and patterns used in the FuelSupply component.
2. All existing functionality is preserved, including:
   - Displaying and editing fuel code data
   - Adding new rows
   - Duplicating rows
   - Deleting rows
   - Validation of data
   - Cloning functionality
3. The refactored component correctly interacts with the backend API, including saving changes and retrieving data.
4. The user interface remains consistent with the current design, despite the underlying changes.
5. Performance is maintained or improved compared to the current implementation.
6. All existing unit tests pass, and new tests are added or updated as necessary.

## Development Checklist
- [ ] Review the current FuelCode component implementation and the new FuelSupply component
- [ ] Refactor the fuelCodeColDefs to match the new structure
- [ ] Update the AddRowsDropdownButton component to work with the new setup
- [ ] Refactor the FuelCodeActions component to align with the FuelSupplyActions implementation
- [ ] Update the main AddFuelCode component to use the new grid setup
- [ ] Ensure all API interactions (useSaveFuelCode, useFuelCodeOptions, etc.) are correctly implemented
- [ ] Maintain the cloning functionality, ensuring it works with the new setup
- [ ] Update or add unit tests to cover the refactored code
- [ ] Perform manual testing to ensure all functionality works as expected
- [ ] Update any relevant documentation

## Additional Notes
- Pay special attention to the async suggestion editors (for company, contact name, contact email)
- Ensure that the date editors (application date, approval date, effective date, expiration date) are correctly implemented
- Verify that the multi-select fields (feedstock transport mode, finished fuel transport mode) maintain their functionality
- Double-check that the fuel production facility fields (city, province/state, country) maintain their interdependent behavior
- Coordinate with the team to ensure this refactor aligns with any ongoing work or planned changes to the FuelCode feature

**Comment by airinggov** [comment]
The Feedstock/Location and Fuel Production City/Province/Country fields don't save new values, only existing (predictive) values can be saved.

**Comment by AlexZorkin** [comment]
Fixed the autocomplete component to work with custom inputs for our new ag-grid implementation.

**Comment by airinggov** [comment]
Feedstock/Location now will save new info but Fuel Production City/Province/Country still don't
